source 'https://rubygems.org' do
	# gem 'cocoapods', '1.7.5'
# gem 'cocoapods', '1.10.0.beta.2'
  gem 'cocoapods', :path => '/Users/dimitris/Development/ios/cocoapods-mine'
  gem 'cocoapods-core', :path => '/Users/dimitris/Development/ios/cocoapods-core-mine'
  gem 'xcodeproj', :path => '/Users/dimitris/Development/ios/cocoapods-xcodeproj-mine'

  # gem 'cocoapods', '1.8.3'
  # gem 'cocoapods-try', :path => '../cocoapods-try'
  # gem 'cocoapods-trunk', '1.4.0'

  # gem 'cocoapods-core', '1.8.0.beta.2'
  # gem 'irb'
  # gem 'xcactivitylog', :git => 'https://github.com/segiddins/xcactivitylog.git', :branch => 'master'
  # gem 'build_execution', '~> 1.3'
  # gem 'ruby-graphviz'
  # gem 'eventstream-client', '~> 1.1'
  # gem 'terminal-table', '~> 1.8.0'
  # gem 'build_execution', '~> 1.3'
  # gem 'ensure-encoding', '0.1'
end
